//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Domain.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Booking.Domain.Entities.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể hoàn thành booking này.
        /// </summary>
        public static string IsCanNotCheckDoneBooking {
            get {
                return ResourceManager.GetString("IsCanNotCheckDoneBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại một booking đã được thuê ở phòng này hoặc đã tồn tại một booking được approved.
        /// </summary>
        public static string IsExistsApprovedBooking {
            get {
                return ResourceManager.GetString("IsExistsApprovedBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng này đã tồn tại.
        /// </summary>
        public static string IsExistsNameRoom {
            get {
                return ResourceManager.GetString("IsExistsNameRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đánh giá phòng này rồi!!!.
        /// </summary>
        public static string IsExistsUserReview {
            get {
                return ResourceManager.GetString("IsExistsUserReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy booking.
        /// </summary>
        public static string IsNotFoundBooking {
            get {
                return ResourceManager.GetString("IsNotFoundBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy vị trí.
        /// </summary>
        public static string IsNotFoundLocation {
            get {
                return ResourceManager.GetString("IsNotFoundLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông báo.
        /// </summary>
        public static string IsNotFoundNotifiation {
            get {
                return ResourceManager.GetString("IsNotFoundNotifiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đánh giá.
        /// </summary>
        public static string IsNotFoundReview {
            get {
                return ResourceManager.GetString("IsNotFoundReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy phòng.
        /// </summary>
        public static string IsNotFoundRoom {
            get {
                return ResourceManager.GetString("IsNotFoundRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không phải là quản trị viên của vị trí này.
        /// </summary>
        public static string IsNotOwnerLocation {
            get {
                return ResourceManager.GetString("IsNotOwnerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không phải là chủ của đánh giá này.
        /// </summary>
        public static string IsNotOwnerReview {
            get {
                return ResourceManager.GetString("IsNotOwnerReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không phải là quản trị viên của phòng này.
        /// </summary>
        public static string IsNotOwnerRoom {
            get {
                return ResourceManager.GetString("IsNotOwnerRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày có thể thuế phải lớn hơn thời gian hiện tại.
        /// </summary>
        public static string IsNotValidAvailableDay {
            get {
                return ResourceManager.GetString("IsNotValidAvailableDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu thuê phải lớn hơn thời gian phòng trống và lớn hơn thời gian hiện tại.
        /// </summary>
        public static string IsNotValidStartDay {
            get {
                return ResourceManager.GetString("IsNotValidStartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng này đang có người thuê.
        /// </summary>
        public static string RoomIsHired {
            get {
                return ResourceManager.GetString("RoomIsHired", resourceCulture);
            }
        }
    }
}
